apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    run: app
spec:
  selector:
    run: app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: app
    spec:
      containers:
      - name: php-fpm
        image: ahahmed/php-mysqli:5
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        volumeMounts:
        - name: dbconn
          mountPath: /code/conn.php
          subPath: conn.php
          readOnly: true
        - name: www-storage
          mountPath: /var/www/html
        lifecycle:
          postStart:
             exec:
               command: ["/bin/sh", "-c", "cp -r /code/. /var/www/html"]
      - name: nginx
        image: nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: www-storage
          mountPath: /var/www/html
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: www-storage
        persistentVolumeClaim:
          claimName: pv-www-claim
      - name: nginx-config-volume
        configMap:
          name: nginx-config
          items:
           - key: default.conf
             path: default.conf
      - name: dbconn
        secret:
          secretName: dbconn
    

